/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.resortfrontdesk;

/**
 *
 * @author admin
 */
public class FrontDeskManagement extends javax.swing.JFrame {

    /**
     * Creates new form FrontDeskManagement
     */
    public FrontDeskManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ReservationLogsButton = new javax.swing.JButton();
        CheckInLogsButton = new javax.swing.JButton();
        WalkInLogsButton = new javax.swing.JButton();
        CancelReservationButton = new javax.swing.JButton();
        CheckOutButton = new javax.swing.JButton();
        RoomsButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(48, 160, 224));

        jPanel6.setBackground(new java.awt.Color(0, 107, 187));

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Resort Front Desk System - Management");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(35, 35, 35))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(25, 25, 25))
        );

        ReservationLogsButton.setBackground(new java.awt.Color(48, 160, 224));
        ReservationLogsButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ReservationLogsButton.setForeground(new java.awt.Color(255, 255, 255));
        ReservationLogsButton.setText("Reservation Logs");
        ReservationLogsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservationLogsButtonActionPerformed(evt);
            }
        });

        CheckInLogsButton.setBackground(new java.awt.Color(48, 160, 224));
        CheckInLogsButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CheckInLogsButton.setForeground(new java.awt.Color(255, 255, 255));
        CheckInLogsButton.setText("Check-In Logs");
        CheckInLogsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckInLogsButtonActionPerformed(evt);
            }
        });

        WalkInLogsButton.setBackground(new java.awt.Color(48, 160, 224));
        WalkInLogsButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        WalkInLogsButton.setForeground(new java.awt.Color(255, 255, 255));
        WalkInLogsButton.setText("Walk-In Logs");
        WalkInLogsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WalkInLogsButtonActionPerformed(evt);
            }
        });

        CancelReservationButton.setBackground(new java.awt.Color(48, 160, 224));
        CancelReservationButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CancelReservationButton.setForeground(new java.awt.Color(255, 255, 255));
        CancelReservationButton.setText("Cancel Reservation");
        CancelReservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelReservationButtonActionPerformed(evt);
            }
        });

        CheckOutButton.setBackground(new java.awt.Color(48, 160, 224));
        CheckOutButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CheckOutButton.setForeground(new java.awt.Color(255, 255, 255));
        CheckOutButton.setText("Check-Out");
        CheckOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutButtonActionPerformed(evt);
            }
        });

        RoomsButton.setBackground(new java.awt.Color(48, 160, 224));
        RoomsButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RoomsButton.setForeground(new java.awt.Color(255, 255, 255));
        RoomsButton.setText("Rooms");
        RoomsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomsButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(221, 196, 169));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(WalkInLogsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CancelReservationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CheckOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CheckInLogsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(ReservationLogsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(RoomsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(242, 242, 242))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CheckOutButton)
                .addGap(18, 18, 18)
                .addComponent(CancelReservationButton)
                .addGap(18, 18, 18)
                .addComponent(CheckInLogsButton)
                .addGap(18, 18, 18)
                .addComponent(ReservationLogsButton)
                .addGap(18, 18, 18)
                .addComponent(WalkInLogsButton)
                .addGap(18, 18, 18)
                .addComponent(RoomsButton)
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CheckOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutButtonActionPerformed
        CheckOut proceed1 = new CheckOut();
        proceed1.setVisible(true);
        dispose();
    }//GEN-LAST:event_CheckOutButtonActionPerformed

    private void CancelReservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelReservationButtonActionPerformed
        CancelReservation proceed2 = new CancelReservation();
        proceed2.setVisible(true);
        dispose();
    }//GEN-LAST:event_CancelReservationButtonActionPerformed

    private void WalkInLogsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WalkInLogsButtonActionPerformed
        WalkInLogs proceed3 = new WalkInLogs();
        proceed3.setVisible(true);
        dispose();
    }//GEN-LAST:event_WalkInLogsButtonActionPerformed

    private void ReservationLogsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservationLogsButtonActionPerformed
        ReservationLogs proceed5 = new ReservationLogs();
        proceed5.setVisible(true);
        dispose();
    }//GEN-LAST:event_ReservationLogsButtonActionPerformed

    private void CheckInLogsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckInLogsButtonActionPerformed
        CheckInLogs proceed4 = new CheckInLogs();
        proceed4.setVisible(true);
        dispose();
    }//GEN-LAST:event_CheckInLogsButtonActionPerformed

    private void RoomsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomsButtonActionPerformed
       Rooms proceed5 = new Rooms();
       proceed5.setVisible(true);
       dispose();
       
    }//GEN-LAST:event_RoomsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrontDeskManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrontDeskManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrontDeskManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrontDeskManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrontDeskManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelReservationButton;
    private javax.swing.JButton CheckInLogsButton;
    private javax.swing.JButton CheckOutButton;
    private javax.swing.JButton ReservationLogsButton;
    private javax.swing.JButton RoomsButton;
    private javax.swing.JButton WalkInLogsButton;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
