/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.resortfrontdesk;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Walk_In extends javax.swing.JFrame {
    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    /**
     * Creates new form Walk_In
     */
    public Walk_In() {
        initComponents();
        Connection();
    }
    
     public void Connection(){
          try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/resortfrontdesk","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Walk_In.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Walk_In.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
     
private int calculateTotalCost() {
    int baseCost = 0;

    // Customize the room rates based on your requirements
    if (daytimeCheckBox.isSelected()) {
        baseCost += 50; 
    }

    if (nighttimeCheckBox.isSelected()) {
        baseCost += 80; 
    }

    int adultRate = 150;
    int kidRate = 60;

    int numAdults = adultratingsBox.isSelected() ? 1 : 0;
    int numKids = kidratingsBox.isSelected() ? 1 : 0;

    baseCost += (numAdults * adultRate) + (numKids * kidRate);

    // Apply 5 percent discount for senior citizens
    if (cbSeniorCitizen.isSelected()) {
        int seniorDiscount = (int) (baseCost * 0.05);
        baseCost -= seniorDiscount;
    }

    // Apply 5 percent discount for PWDs
    if (cbPWD.isSelected()) {
        int pwdDiscount = (int) (baseCost * 0.05);
        baseCost -= pwdDiscount;
    }

    return baseCost;
}

    private void updateTotalCost() {
    int totalCost = calculateTotalCost();
    walkinPriceLabel.setText("PRICE: PHP " + totalCost);
}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        guestName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        guestPhNum = new javax.swing.JTextField();
        guestAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        daytimeCheckBox = new javax.swing.JCheckBox();
        nighttimeCheckBox = new javax.swing.JCheckBox();
        adultratingsBox = new javax.swing.JCheckBox();
        kidratingsBox = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        cbSeniorCitizen = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        cbPWD = new javax.swing.JCheckBox();
        SubmitButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        walkinPriceLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 107, 187));

        jLabel2.setText("Resort Front Desk System - Walk-In");
        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel2)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel1.setText("Name:");

        jLabel3.setText("Phone Number:");

        jLabel4.setText("Address:");

        daytimeCheckBox.setText("Day Time Swimming");
        daytimeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daytimeCheckBoxActionPerformed(evt);
            }
        });

        nighttimeCheckBox.setText("Night Time Swimming");
        nighttimeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nighttimeCheckBoxActionPerformed(evt);
            }
        });

        adultratingsBox.setText("Adult");
        adultratingsBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adultratingsBoxActionPerformed(evt);
            }
        });

        kidratingsBox.setText("Kid");
        kidratingsBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kidratingsBoxActionPerformed(evt);
            }
        });

        jLabel7.setText("Are you a:");

        cbSeniorCitizen.setText("Senior Citizen");
        cbSeniorCitizen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSeniorCitizenActionPerformed(evt);
            }
        });

        jLabel8.setText("Are you a:");

        cbPWD.setText("PWD");
        cbPWD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPWDActionPerformed(evt);
            }
        });

        SubmitButton.setText("SUBMIT");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        walkinPriceLabel.setText("PRICE:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(guestAddress)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(guestPhNum, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guestName, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbPWD))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbSeniorCitizen))
                            .addComponent(walkinPriceLabel))
                        .addGap(36, 36, 36))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(daytimeCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nighttimeCheckBox))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(adultratingsBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kidratingsBox)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(SubmitButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guestName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cbSeniorCitizen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbPWD))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guestPhNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guestAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(walkinPriceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adultratingsBox)
                    .addComponent(kidratingsBox))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daytimeCheckBox)
                    .addComponent(nighttimeCheckBox))
                .addGap(18, 18, 18)
                .addComponent(SubmitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void daytimeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daytimeCheckBoxActionPerformed
        updateTotalCost();
        if(daytimeCheckBox.isSelected()){
            nighttimeCheckBox.setVisible(false);
        } else {
            nighttimeCheckBox.setVisible(true);
        }
    }//GEN-LAST:event_daytimeCheckBoxActionPerformed

    private void nighttimeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nighttimeCheckBoxActionPerformed
        updateTotalCost();
         if(nighttimeCheckBox.isSelected()){
            daytimeCheckBox.setVisible(false);
        } else {
            daytimeCheckBox.setVisible(true);
        }
    }//GEN-LAST:event_nighttimeCheckBoxActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        try {
            int totalCost = calculateTotalCost();
            
            String sql = "INSERT INTO guestwalkin (name, phnum, address, isadultratings, iskidratings, daytimeswim, nighttimeswim, isSeniorCitizen, isPWD, totalCost) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            pst = con.prepareStatement(sql);
            
            pst.setString(1,guestName.getText());
            pst.setString(2,guestPhNum.getText());
            pst.setString(3, guestAddress.getText());
            pst.setBoolean(4, adultratingsBox.isSelected());
            pst.setBoolean(5, kidratingsBox.isSelected());
            pst.setBoolean(6, daytimeCheckBox.isSelected());
            pst.setBoolean(7, nighttimeCheckBox.isSelected());
            pst.setBoolean(8, cbSeniorCitizen.isSelected());
            pst.setBoolean(9, cbPWD.isSelected());
            pst.setInt(10, totalCost);
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Walk-In recorded successfully. Total Cost: PHP" + totalCost);
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Walk_In.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error recording walk-in. Please try again.");
        }
        dispose();
        ResortFrontDesk home1 = new ResortFrontDesk();
        home1.setVisible(true);
    
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void kidratingsBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kidratingsBoxActionPerformed
        updateTotalCost();
        if(kidratingsBox.isSelected()){
           adultratingsBox.setVisible(false);
       } else {
           adultratingsBox.setVisible(true);
       }
        
    }//GEN-LAST:event_kidratingsBoxActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        dispose();
        ResortFrontDesk home2 = new ResortFrontDesk();
        home2.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void adultratingsBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adultratingsBoxActionPerformed
       updateTotalCost();
       if(adultratingsBox.isSelected()){
           kidratingsBox.setVisible(false);
       } else {
           kidratingsBox.setVisible(true);
       }
       
    }//GEN-LAST:event_adultratingsBoxActionPerformed

    private void cbSeniorCitizenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSeniorCitizenActionPerformed
        updateTotalCost();
    }//GEN-LAST:event_cbSeniorCitizenActionPerformed

    private void cbPWDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPWDActionPerformed
        updateTotalCost();
    }//GEN-LAST:event_cbPWDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Walk_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Walk_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Walk_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Walk_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Walk_In().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SubmitButton;
    private javax.swing.JCheckBox adultratingsBox;
    private javax.swing.JButton backButton;
    private javax.swing.JCheckBox cbPWD;
    private javax.swing.JCheckBox cbSeniorCitizen;
    private javax.swing.JCheckBox daytimeCheckBox;
    private javax.swing.JTextField guestAddress;
    private javax.swing.JTextField guestName;
    private javax.swing.JTextField guestPhNum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox kidratingsBox;
    private javax.swing.JCheckBox nighttimeCheckBox;
    private javax.swing.JLabel walkinPriceLabel;
    // End of variables declaration//GEN-END:variables
}
